version: '3.3'
services:
  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir-blocks /data/mimir-ruler /data/mimir-alertmanager /data/tempo /data/loki-data /data/loki-ruler && minio server /data --console-address :9001"]
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=supersecret
    volumes:
      - minio-data:/data
    ports:
      - "9001:9001"
  
  redis:
    image: redis:6.2.7
  
  mysql:
    image: mysql:5.7.39
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret

  app:
    image: app:0.0.1
    ports:
      - "8080:8080"
      
  mimir:
    image: grafana/mimir:2.2.0
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/data

  loki:
    image: grafana/loki:2.6.1
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    depends_on:
      - minio

  tempo:
    image: grafana/tempo:1.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "14268"      # jaeger
      - "3200:3200"  # tempo
    restart: on-failure
    depends_on:
      - minio

  agent:
    image: grafana/agent:v0.27.0
    volumes:
      - ./config/agent.yaml:/etc/agent-config/agent.yaml
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    ports:
      - "12345:12345"
    depends_on:
      - mimir
      - app

  grafana:
    image: grafana/grafana:9.1.3
    pull_policy: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - "3000:3000"

volumes:
  mimir-data:
  tempo-data:
  minio-data:

