version: '3.3'
services:
  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir-blocks /data/mimir-ruler /data/mimir-alertmanager /data/tempo /data/loki-data /data/loki-ruler && minio server /data --console-address :9001"]
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=supersecret
    volumes:
      - minio-data:/data
    ports:
      - "9001:9001"
  
  redis:
    image: redis:6.2.7
  
  mysql:
    image: mysql:5.7.39
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret

  grafana:
    image: grafana/grafana:9.1.2
    pull_policy: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    volumes:
      - ./config/grafana/grafana-provisioning-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./config/grafana/grafana-provisioning-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      - ./config/grafana/lgtm-demo.json:/var/lib/grafana/dashboards/lgtm-demo.json:ro
    ports:
      - "3000:3000"
      
  mimir:
    image: grafana/mimir:2.4.0
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/data

  loki:
    image: grafana/loki:2.6.1
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    depends_on:
      - minio

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "14268"    
      - "4317"
      - "3200:3200"
    depends_on:
      - minio

  collector:
    image: otel/opentelemetry-collector:0.63.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 8889:8889
    depends_on:
      - tempo
      - mimir

  collector-contrib:
    image: otel/opentelemetry-collector-contrib:0.63.1
    command: ["--config=/etc/otel-collector-contrib-config.yaml"]
    volumes:
      - ./config/otel-collector-contrib-config.yaml:/etc/otel-collector-contrib-config.yaml
      - log-data:/var/log
    depends_on:
      - loki

  lb.com:
    image: nginx:1.23.1
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9090:80
    depends_on:
      - mimir
      - loki
      - tempo
  
  app:
    image: app:0.0.1
    ports:
      - "8080:8080"
    volumes:
      - log-data:/var/log
    depends_on:
      - redis
      - mysql
      - collector

volumes:
  mimir-data:
  tempo-data:
  minio-data:
  log-data:

