{
 "title": "LGTM Demo",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceID" }
  ]
 },
 "panels": [
  {
   "title": "App request time duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_durations_histogram_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{filename=\"app.log\"} |= `${traceID}`"
    }
   ]
  },
  {
   "title": "App trace",
   "type": "traces",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 8 },
   "targets": [
    { "query": "${traceID}" }
   ]
  },
  {
   "title": "CPU Profiling",
   "type": "flamegraph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "labelSelector": "{instance=\"app:6060\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  }
 ]
}