metrics:
  wal_directory: /tmp/grafana-agent/wal
  
  global:
    scrape_interval: 5s
    external_labels:
      cluster: demo
      namespace: demo
      
  configs:
    - name: demo
      scrape_configs:
        - job_name: mimir
          static_configs:
            - targets: [ 'mimir:8080' ]
        - job_name: exemplar-app
          static_configs:
            - targets: [ 'app:8080' ]
      remote_write:
        - url: http://mimir:8080/api/v1/push
          send_exemplars: true
          headers:
            X-Scope-OrgID: demo
            
